name: speedbridge2
version: ${version}
main: com.github.tofpu.speedbridge2.bukkit.plugin.BukkitPlugin
authors: [ Tofpu ]
website: https://github.com/Tofpu
api-version: 1.13
depend:
  - WorldEdit
softdepend:
  - PlaceholderAPI
