name: SpeedBridge2
version: ${version}
main: io.tofpu.speedbridge2.plugin.SpeedBridgePlugin
authors: [ Tofpu ]
website: https://www.spigotmc.org/resources/100619/
api-version: 1.13
depend:
  - WorldEdit
softdepend:
  - PlaceholderAPI
