name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: '1.0.0'
        required: true
      path:
        description: 'build/libs/SpeedBridge2-*.jar'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: shadowJar
          
    - name: Upload jar
      uses: AButler/upload-release-assets@v2.0
      with:
        release-tag: ${{ github.event.inputs.release-tag }}
        files: ${{ github.event.inputs.path }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
